# Evaluation of the Utils class

In [ ]:
import numpy as np
from mnplib.utils import empirical_distribution

### Categorical Vectors

In [2]:
x = np.array(["cat", "cat", "dog", "bird", "dog", "cat"])
summary = empirical_distribution(columns=[x], numeric=[False])

In [ ]:
print(summary.states)
print(summary.counts)
print(summary.probabilities)
# (1/2) * (-np.log2(1/2)) + (1/3) * (-np.log2(1/3)) + (1/6) * (-np.log2(1/6)) = 1.46
print(summary.entropy)
# 3 * (-np.log2(1/2)) + 2 * (-np.log2(1/3)) + 1 * (-np.log2(1/6)) = 8.75
print(summary.code_length)

[[0]
 [1]
 [2]]
[3. 2. 1.]
[0.5        0.33333333 0.16666667]
1.4591479170272448
8.754887502163468


### Numerical Vectors

In [ ]:
x = np.array([1.0, 1.2, 1.3, 4.8, 5.0, 5.2])
summary = empirical_distribution(columns=[x], numeric=[True], n_bins=2)

In [11]:
print(summary.states)
print(summary.counts)
print(summary.probabilities)
print(summary.entropy)
print(summary.code_length)

[[0]
 [1]]
[3. 3.]
[0.5 0.5]
1.0
6.0


Automated selection of the number of bins

In [16]:
np.ceil(2 * 10**(1/3))

np.float64(5.0)

In [15]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# 2 * n**(1/3) = 
summary = empirical_distribution( columns=[x], numeric=[True], n_bins="auto")
print(summary.states)
print(summary.counts)

[[0]
 [1]
 [2]
 [3]
 [4]]
[2. 2. 2. 2. 2.]


### Join Empirical Distributions

In [ ]:
# (A,0), (A,0), (B,1), (B,1), (B,0), (A,0)
x = np.array(["A", "A", "B", "B", "B", "A"])
y = np.array([0, 0, 1, 1, 0, 0])
summary = empirical_distribution(columns=[x, y], numeric=[False, False])

In [18]:
print(summary.states)
print(summary.counts)
print(summary.probabilities)
print(summary.entropy)
print(summary.code_length)

[[0 0]
 [1 0]
 [1 1]]
[3. 1. 2.]
[0.5        0.16666667 0.33333333]
1.4591479170272446
8.754887502163466


In [22]:
# (A,0,0), (A,0,0), (B,1,0), (B,1,1), (B,0,1), (A,0,1)
x = np.array(["A", "A", "B", "B", "B", "A"])
y = np.array([0, 0, 1, 1, 0, 0])
z = np.array([0, 0, 0, 1, 1, 1])
summary = empirical_distribution(columns=[x, y, z], numeric=[False, False, False])

In [23]:
print(summary.states)
print(summary.counts)
print(summary.probabilities)
print(summary.entropy)
print(summary.code_length)

[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[2. 1. 1. 1. 1.]
[0.33333333 0.16666667 0.16666667 0.16666667 0.16666667]
2.2516291673878226
13.509775004326936
